# # 8-jdk-alpine
version: "3"
services:
  mongodb:
    image: mongo:4.0.0
    container_name: mongodb
    ports:
    - 27017:27017
    command: --smallfiles

  account:
    build : ./Account
    image: springio/account
    ports:
    - 8081:8081
    links:
    - mongodb
    environment:
      spring.data.mongodb.uri: mongodb://mongodb:27017/account
    container_name: account

  bank:
    build : ./Bank
    image: springio/bank
    ports:
    - 8080:8080
    links:
    - mongodb
    environment:
      spring.data.mongodb.uri: mongodb://mongodb:27017/bank
    container_name: bank

  recommandation:
    build : ./Recommandation
    image: python/recommandation
    ports:
    - 8000:80
    links:
    - mongodb
    environment:
      spring.data.mongodb.uri: mongodb://mongodb:27017/recommandation
    depends_on:
      - account
    container_name: recommendation
